### ISSUE TITLE
Invisible after Spectator mode if on a earlier version

### ISSUE THREAD

**Issue by M9GLiquid** [MineTheCube/ClientStats#1]
Issue: When a player of a earlier version exits spectator and goes to survival they become invisible (Only head showing)

Reason:
Minecraft had a bug with previous versions:
https://forums.multiplay.com/minecraft/78389-fix-quot-invincible-quot-glitch

Suggestion to fix:
 - Update theire skin?
 - Update theire invisibility?

Regards,
Thomas

**Comment by MineTheCube** [comment]
Sorry, but this isn't related to ClientStats.

Should be an issue with Spigot itself: https://hub.spigotmc.org/jira
