### ISSUE TITLE
Version unknown

### ISSUE THREAD

**Issue by Epikest** [MineTheCube/ClientStats#15]
![image](https://user-images.githubusercontent.com/45499416/174946064-f2fab5b0-15bf-4855-860d-2abb065e47bb.png)
```log
[06:49:52 ERROR]: [ClientStats] Missing version: versions.758
```
see: https://github.com/MineTheCube/ClientStats/issues/11

**Comment by MineTheCube** [comment]
hi!

recent versions were added here (90732bfad54cc609fde2ded6b16933bc1f5fe151), and I pushed an update to spigot, so be sure to check it out!

links are in the readme: https://github.com/MineTheCube/ClientStats#readme
