### ISSUE TITLE
Add a License file

### ISSUE THREAD

**Issue by HowardZHY** [MineTheCube/ClientStats#17]

**Comment by djhbznz** [comment]
作者不像是还想做这个插件的样子

**Comment by djhbznz** [comment]
你是要续作？？？？

**Comment by MineTheCube** [comment]
i've added a license, so you guys can takeover and make your own :)

also, the only thing to do to make it work on recent version is to fill the `versions` section of your config: https://github.com/MineTheCube/ClientStats/blob/master/src/main/resources/config.yml#L69

you can get those here: https://github.com/PrismarineJS/minecraft-data/blob/master/data/pc/common/protocolVersions.json#L3-L4
